name: sinabro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- 공통 의존성 ---
  kakao_flutter_sdk_user: ^1.3.1
  kakao_flutter_sdk_auth: ^1.3.1
  google_sign_in: ^6.3.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.9
  shared_preferences: ^2.1.1
  audioplayers: ^5.2.0
  provider: ^6.1.1
  http: ^1.1.0
  just_audio: ^0.9.36
  audio_session: ^0.1.21
  googleapis_auth: ^1.6.0 # 구글 번역 api 
  html_unescape: ^2.0.0 # 특수문자를 안전하게 전달

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
  - family: Inter
    fonts:
      - asset: assets/font/Inter-Light.ttf
        weight: 300
      - asset: assets/font/Inter-Medium.ttf
        weight: 500
      - asset: assets/font/Inter-Bold.ttf
        weight: 700

  assets:
    # --- 공통 Img ---
    - assets/audio/tts/
    - assets/img/contents/gameWrite/end_succes.png
    - assets/img/contents/gameWrite/theme/write_game_3_cup_deactivation.png
    - assets/img/auth/
    - assets/img/character/
    - assets/img/logo/
    - assets/img/contents/stickerBook/
    - assets/img/contents/stickerBook/stickers/

    - assets/img/contents/gameListen/
    - assets/img/contents/gameListen/level1/
    - assets/img/contents/gameListen/level1/answer/
    - assets/img/contents/gameListen/level1/theme/
    - assets/img/contents/gameListen/level2/
    - assets/img/contents/gameListen/level2/answer/
    - assets/img/contents/gameListen/level2/result/
    - assets/img/contents/gameListen/level2/theme/
    - assets/img/contents/gameListen/level3/
    - assets/img/contents/gameListen/level3/answer/
    - assets/img/contents/gameListen/level3/theme/
    - assets/img/contents/gameListen/tutorial/
    - assets/img/contents/gameListen/chapter/

    - assets/img/contents/gameWrite/
    - assets/img/contents/gameWrite/chapter/
    
    - assets/img/contents/studyListen/
    - assets/img/contents/studyListen/level1/
    - assets/img/contents/studyListen/level1/colors/
    - assets/img/contents/studyListen/level1/animals/
    - assets/img/contents/studyListen/level2/
    - assets/img/contents/studyListen/level2/main_keyword/
    - assets/img/contents/studyListen/level2/main_topic/
    - assets/img/contents/studyListen/level2/story/
    - assets/img/contents/studyListen/level3/
    - assets/img/contents/studyListen/level3/main_keyword/
    - assets/img/contents/studyListen/level3/main_topic/
    - assets/img/contents/studyListen/level3/story/
    - assets/img/contents/studyWrite/
    - assets/img/icon/
    - assets/img/icon/popup/
    - assets/img/leveltest/
    - assets/img/pageMain/
    - assets/img/pageSetting/

    - assets/audio/bgm/
    - assets/audio/effect/
    - assets/audio/tts/levelTest/
    - assets/audio/tts/gameListen/
    - assets/audio/tts/gameListen/practice/
    - assets/audio/tts/gameListen/level1/
    - assets/audio/tts/gameListen/level2/
    - assets/audio/tts/gameListen/level3/
    - assets/audio/tts/gameWrite/
    - assets/audio/tts/gameWrite/level1/
    - assets/audio/tts/gameWrite/level2/
    - assets/audio/tts/gameWrite/level3/
    - assets/audio/tts/studyListen/
    - assets/audio/tts/studyListen/level1/animals/
    - assets/audio/tts/studyListen/level1/colors/
    - assets/audio/tts/studyListen/level2/emotions/
    - assets/audio/tts/studyListen/level2/family/
    - assets/audio/tts/studyListen/level2/numbers/
    - assets/audio/tts/studyListen/level3/daily/
    - assets/audio/tts/studyWrite/
    - assets/audio/tts/studyWrite/level1/
    - assets/audio/tts/studyWrite/level2/
    - assets/audio/tts/studyWrite/level3/
