name: sinabro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.1
  audioplayers: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/auth/
    - assets/img/character/
    - assets/img/contents/gameListen/
    - assets/img/contents/gameWrite/
    - assets/img/contents/studyListen/
    - assets/img/contents/studyWrite/
    - assets/img/icon/
    - assets/img/pageMain/
    - assets/img/pageSetting/

    - assets/audio/bgm/
    - assets/audio/effect/
    - assets/audio/tts/gameListen/
    - assets/audio/tts/gameWrite/
    - assets/audio/tts/studyListen/
    - assets/audio/tts/studyListen/test/
    - assets/audio/tts/studyWrite/
    - assets/audio/tts/studyWrite/test/